defaults:
  - backbone: K2L2_test
  - _self_

job:
  device_type: CPU
  scheduler:
    mode: LOCAL
    ranks_per_node: 1
    num_nodes: 1
  debug: True
  run_dir: outputs/horm_uma_hessian_from_scratch_cpu
  run_name: horm_uma_hessian_cpu
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: andreas-burger
    project: uma
    group: horm_uma_hessian
    job_type: training

moe_layer_type: pytorch
num_moe_experts: 0
act_type: s2
ff_type: grid
max_neighbors: 30
cutoff_radius: 6
num_layers_hessian: 1
cutoff_hessian: 100.0
fully_connected_hessian: True
use_pbc_hessian: False
epochs: null
steps: 1
eval_every_n_steps: 1
eval_every_n_epochs: null
batch_size: 1
train_max_batches: null
eval_max_batches: 4
bf16: False
normalizer_rmsd: 1.0
direct_forces_coef: 30
hessian_coef: 30
hessian_loss_mode: mae
regress_stress: False
direct_forces: True
dataset_list: ["omol"]
exclude_keys: []

omol_train:
  splits:
    train:
      src: data/horm_atomic/ts1x-val.atomic.lmdb
      metadata_path: data/horm_atomic/ts1x-val.atomic.metadata.npz
      first_n: 128
  format: atomic_lmdb
  transforms:
    common_transform:
      dataset_name: omol
    molecule_cell_transform:
      cell_size: 120.0

omol_val:
  splits:
    val:
      src: data/horm_atomic/ts1x-val.atomic.lmdb
      metadata_path: data/horm_atomic/ts1x-val.atomic.metadata.npz
      first_n: 32
  format: atomic_lmdb
  transforms:
    common_transform:
      dataset_name: omol
    molecule_cell_transform:
      cell_size: 120.0

train_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    omol: ${omol_train}
  combined_dataset_config: { sampling: {type: temperature, temperature: 1.0} }

val_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    omol: ${omol_val}
  combined_dataset_config: { sampling: {type: temperature, temperature: 1.0} }

train_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${train_dataset}
  batch_sampler_fn:
    _target_: fairchem.core.common.data_parallel.BalancedBatchSampler
    _partial_: True
    batch_size: ${batch_size}
    shuffle: True
    seed: 0
  num_workers: 0
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

eval_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${val_dataset}
  batch_sampler_fn:
    _target_: fairchem.core.common.data_parallel.BalancedBatchSampler
    _partial_: True
    batch_size: ${batch_size}
    shuffle: False
    seed: 0
  num_workers: 0
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

heads:
  hessian:
    module: fairchem.core.models.uma.escn_md.Hessian_Head
    num_layers_hessian: ${num_layers_hessian}
    cutoff_hessian: ${cutoff_hessian}
    fully_connected_hessian: ${fully_connected_hessian}
    use_pbc_hessian: ${use_pbc_hessian}

tasks:
- _target_: fairchem.core.units.mlip_unit.mlip_unit.Task
  name: hessian
  level: system
  property: hessian
  loss_fn:
    _target_: fairchem.core.modules.loss.HessianLoss
    mode: ${hessian_loss_mode}
    reduction: structure_mean
    coefficient: ${hessian_coef}
  out_spec:
    dim: [1]
    dtype: float32
  normalizer:
    _target_: fairchem.core.modules.normalization.normalizer.Normalizer
    mean: 0.0
    rmsd: ${normalizer_rmsd}
  datasets:
    - omol
  metrics:
    - hessian_mae
    - hessian_mse
    - hessian_rmse
    - hessian_eckart_eigenvalue_mae
    - hessian_eckart_eigvec1_cos
    - hessian_eckart_eigvec2_cos

runner:
  _target_: fairchem.core.components.train.train_runner.TrainEvalRunner
  train_dataloader: ${train_dataloader}
  eval_dataloader: ${eval_dataloader}
  train_eval_unit:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.MLIPTrainEvalUnit
    job_config: ${job}
    tasks: ${tasks}
    model:
      _target_: fairchem.core.models.base.HydraModel
      backbone: ${backbone}
      heads: ${heads}
    optimizer_fn:
      _target_: torch.optim.AdamW
      _partial_: true
      lr: 8e-4
      weight_decay: 1e-3
    cosine_lr_scheduler_fn:
      _target_: fairchem.core.units.mlip_unit.mlip_unit._get_consine_lr_scheduler
      _partial_: true
      warmup_factor: 0.2
      warmup_epochs: 0.01
      lr_min_factor: 0.01
      epochs: ${epochs}
      steps: ${steps}
    print_every: 1
    clip_grad_norm: 100
    bf16: ${bf16}
  max_epochs: ${epochs}
  max_steps: ${steps}
  max_train_steps_per_epoch: ${train_max_batches}
  evaluate_every_n_steps: ${eval_every_n_steps}
  evaluate_every_n_epochs: ${eval_every_n_epochs}
  max_eval_steps_per_epoch: ${eval_max_batches}
  callbacks:
    - _target_: fairchem.core.components.train.train_runner.TrainCheckpointCallback
      checkpoint_every_n_steps: 1
      max_saved_checkpoints: 2
